import type { FlowDefinition } from "./types.js";

const menu = (
  id: string,
  templateId: string,
  choices: Array<{ key: string; label: string; target: string; aliases?: string[] }>,
  parentId?: string,
): import("./types.js").FlowNode => ({
  id,
  ...(parentId ? { parentId } : {}),
  action: "menu",
  templateId,
  choices: choices.map((c) => ({
    key: c.key,
    label: c.label,
    targetNodeId: c.target,
    ...(c.aliases ? { aliases: c.aliases } : {}),
  })),
});

export const V1_FLOW: FlowDefinition = {
  version: "deterministic-v1",
  entryNodeId: "home",
  nodes: {
    home: menu("home", "home.v1", [
      { key: "0", label: "Customer Service", target: "handoff.cs" },
      { key: "1", label: "BELI", target: "buy" },
      { key: "2", label: "INFO PRODUK", target: "product" },
      { key: "3", label: "BANTUAN PESANAN", target: "order" },
      { key: "4", label: "BISNIS / B2B", target: "business" },
      { key: "5", label: "KOMPLAIN", target: "complaint" },
      { key: "6", label: "LAINNYA", target: "other" },
    ]),
    buy: menu("buy", "buy.v1", [
      { key: "0", label: "Customer Service", target: "handoff.cs" },
      { key: "1", label: "Yubie Flour", target: "buy.flour" },
      { key: "2", label: "Yubie Shake", target: "buy.shake" },
      { key: "3", label: "Yubie Ppang", target: "buy.ppang" },
      { key: "4", label: "Yubie Mie", target: "buy.mie" },
      { key: "9", label: "Kembali", target: "home" },
    ], "home"),
    "buy.flour": menu("buy.flour", "buy.flour.v1", [
      { key: "0", label: "Customer Service", target: "handoff.cs" },
      { key: "1", label: "Shopee", target: "buy.flour.shopee" },
      { key: "2", label: "Tokopedia", target: "buy.flour.tokopedia" },
      { key: "9", label: "Kembali", target: "buy" },
    ], "buy"),
    "buy.flour.shopee": { id: "buy.flour.shopee", parentId: "buy.flour", action: "reply", templateId: "buy.flour.marketplace.v1", intent: "WHERE_TO_BUY", risk: "GREEN" },
    "buy.flour.tokopedia": { id: "buy.flour.tokopedia", parentId: "buy.flour", action: "reply", templateId: "buy.flour.marketplace.v1", intent: "WHERE_TO_BUY", risk: "GREEN" },
    "buy.shake": menu("buy.shake", "buy.online.v1", [
      { key: "0", label: "Customer Service", target: "handoff.cs" },
      { key: "1", label: "Belanja online", target: "buy" },
      { key: "9", label: "Kembali", target: "buy" },
    ], "buy"),
    "buy.ppang": menu("buy.ppang", "buy.online.v1", [
      { key: "0", label: "Customer Service", target: "handoff.cs" },
      { key: "1", label: "Belanja online", target: "buy" },
      { key: "9", label: "Kembali", target: "buy" },
    ], "buy"),
    "buy.mie": menu("buy.mie", "buy.online.v1", [
      { key: "0", label: "Customer Service", target: "handoff.cs" },
      { key: "1", label: "Belanja online", target: "buy" },
      { key: "9", label: "Kembali", target: "buy" },
    ], "buy"),
    product: menu("product", "product.v1", [
      { key: "0", label: "Customer Service", target: "handoff.cs" },
      { key: "1", label: "Apa produk ini?", target: "product.description" },
      { key: "2", label: "Cara pakai", target: "product.usage" },
      { key: "3", label: "Resep", target: "product.recipes" },
      { key: "4", label: "Root/varian", target: "product.roots" },
      { key: "5", label: "Bahan/nutrisi/alergen", target: "product.sensitive" },
      { key: "6", label: "Sertifikasi", target: "product.certification" },
      { key: "7", label: "Beli di mana", target: "product.where" },
      { key: "9", label: "Kembali", target: "home" },
    ], "home"),
    "product.description": { id: "product.description", parentId: "product", action: "reply", templateId: "product.fact.v1", intent: "PRODUCT_INFO", risk: "GREEN" },
    "product.usage": { id: "product.usage", parentId: "product", action: "reply", templateId: "product.fact.v1", intent: "USAGE_RECIPE", risk: "GREEN" },
    "product.recipes": { id: "product.recipes", parentId: "product", action: "reply", templateId: "product.fact.v1", intent: "USAGE_RECIPE", risk: "GREEN" },
    "product.roots": { id: "product.roots", parentId: "product", action: "reply", templateId: "product.fact.v1", intent: "PRODUCT_DISCOVERY", risk: "GREEN" },
    "product.sensitive": { id: "product.sensitive", parentId: "product", action: "reply", templateId: "product.sensitive_missing.v1", intent: "ALLERGEN_OR_HEALTH", risk: "RED" },
    "product.certification": { id: "product.certification", parentId: "product", action: "reply", templateId: "product.sensitive_missing.v1", intent: "CERTIFICATION", risk: "AMBER" },
    "product.where": { id: "product.where", parentId: "product", action: "reply", templateId: "buy.flour.v1", intent: "WHERE_TO_BUY", risk: "GREEN" },
    order: menu("order", "order.v1", [
      { key: "0", label: "Customer Service", target: "handoff.cs" },
      { key: "1", label: "Shopee", target: "order.shopee" },
      { key: "2", label: "Tokopedia", target: "order.tokopedia" },
      { key: "9", label: "Kembali", target: "home" },
    ], "home"),
    "order.shopee": menu("order.shopee", "order.issue.v1", [
      { key: "0", label: "Customer Service", target: "handoff.cs" },
      { key: "1", label: "Pengiriman", target: "order.guidance.shipping" },
      { key: "2", label: "Pembayaran", target: "order.guidance.payment" },
      { key: "3", label: "Refund", target: "handoff.refund" },
      { key: "4", label: "Barang salah", target: "handoff.complaint" },
      { key: "5", label: "Rusak", target: "handoff.complaint" },
      { key: "6", label: "Kualitas", target: "handoff.complaint" },
      { key: "7", label: "Lainnya", target: "handoff.cs" },
      { key: "9", label: "Kembali", target: "order" },
    ], "order"),
    "order.tokopedia": menu("order.tokopedia", "order.issue.v1", [
      { key: "0", label: "Customer Service", target: "handoff.cs" },
      { key: "1", label: "Pengiriman", target: "order.guidance.shipping" },
      { key: "2", label: "Pembayaran", target: "order.guidance.payment" },
      { key: "3", label: "Refund", target: "handoff.refund" },
      { key: "4", label: "Barang salah", target: "handoff.complaint" },
      { key: "5", label: "Rusak", target: "handoff.complaint" },
      { key: "6", label: "Kualitas", target: "handoff.complaint" },
      { key: "7", label: "Lainnya", target: "handoff.cs" },
      { key: "9", label: "Kembali", target: "order" },
    ], "order"),
    "order.guidance.shipping": { id: "order.guidance.shipping", parentId: "order", action: "reply", templateId: "order.guidance.v1", intent: "OTHER", risk: "AMBER" },
    "order.guidance.payment": { id: "order.guidance.payment", parentId: "order", action: "reply", templateId: "order.guidance.v1", intent: "OTHER", risk: "AMBER" },
    business: menu("business", "business.v1", [
      { key: "0", label: "Sales", target: "handoff.sales" },
      { key: "1", label: "Sample", target: "business.sample.company" },
      { key: "2", label: "Bulk", target: "business.bulk.company" },
      { key: "3", label: "Product dev", target: "business.dev.type" },
      { key: "4", label: "Wholesale", target: "handoff.sales" },
      { key: "5", label: "Partnership", target: "handoff.sales" },
      { key: "9", label: "Kembali", target: "home" },
    ], "home"),
    "business.sample.company": { id: "business.sample.company", parentId: "business", action: "collect", templateId: "b2b.collect.v1", contextField: "company", nextAfterCollect: "business.sample.use_case", intent: "B2B_SAMPLE", risk: "AMBER" },
    "business.sample.use_case": { id: "business.sample.use_case", parentId: "business", action: "collect", templateId: "b2b.collect.v1", contextField: "useCase", nextAfterCollect: "business.sample.product", intent: "B2B_SAMPLE", risk: "AMBER" },
    "business.sample.product": { id: "business.sample.product", parentId: "business", action: "collect", templateId: "b2b.collect.v1", contextField: "product", nextAfterCollect: "business.sample.location", intent: "B2B_SAMPLE", risk: "AMBER" },
    "business.sample.location": { id: "business.sample.location", parentId: "business", action: "collect", templateId: "b2b.collect.v1", contextField: "location", nextAfterCollect: "handoff.sales", intent: "B2B_SAMPLE", risk: "AMBER" },
    "business.bulk.company": { id: "business.bulk.company", parentId: "business", action: "collect", templateId: "b2b.collect.v1", contextField: "company", nextAfterCollect: "business.bulk.type", intent: "B2B_BULK", risk: "AMBER" },
    "business.bulk.type": { id: "business.bulk.type", parentId: "business", action: "collect", templateId: "b2b.collect.v1", contextField: "businessType", nextAfterCollect: "business.bulk.city", intent: "B2B_BULK", risk: "AMBER" },
    "business.bulk.city": { id: "business.bulk.city", parentId: "business", action: "collect", templateId: "b2b.collect.v1", contextField: "city", nextAfterCollect: "business.bulk.product", intent: "B2B_BULK", risk: "AMBER" },
    "business.bulk.product": { id: "business.bulk.product", parentId: "business", action: "collect", templateId: "b2b.collect.v1", contextField: "product", nextAfterCollect: "business.bulk.volume", intent: "B2B_BULK", risk: "AMBER" },
    "business.bulk.volume": { id: "business.bulk.volume", parentId: "business", action: "collect", templateId: "b2b.collect.v1", contextField: "volume", nextAfterCollect: "business.bulk.timeline", intent: "B2B_BULK", risk: "AMBER" },
    "business.bulk.timeline": { id: "business.bulk.timeline", parentId: "business", action: "collect", templateId: "b2b.collect.v1", contextField: "timeline", nextAfterCollect: "handoff.sales", intent: "B2B_BULK", risk: "AMBER" },
    "business.dev.type": { id: "business.dev.type", parentId: "business", action: "collect", templateId: "b2b.collect.v1", contextField: "businessType", nextAfterCollect: "business.dev.application", intent: "B2B_PRODUCT_DEVELOPMENT", risk: "AMBER" },
    "business.dev.application": { id: "business.dev.application", parentId: "business", action: "collect", templateId: "b2b.collect.v1", contextField: "application", nextAfterCollect: "business.dev.product", intent: "B2B_PRODUCT_DEVELOPMENT", risk: "AMBER" },
    "business.dev.product": { id: "business.dev.product", parentId: "business", action: "collect", templateId: "b2b.collect.v1", contextField: "product", nextAfterCollect: "business.dev.volume", intent: "B2B_PRODUCT_DEVELOPMENT", risk: "AMBER" },
    "business.dev.volume": { id: "business.dev.volume", parentId: "business", action: "collect", templateId: "b2b.collect.v1", contextField: "volume", nextAfterCollect: "business.dev.timeline", intent: "B2B_PRODUCT_DEVELOPMENT", risk: "AMBER" },
    "business.dev.timeline": { id: "business.dev.timeline", parentId: "business", action: "collect", templateId: "b2b.collect.v1", contextField: "timeline", nextAfterCollect: "handoff.sales", intent: "B2B_PRODUCT_DEVELOPMENT", risk: "AMBER" },
    complaint: menu("complaint", "complaint.v1", [
      { key: "0", label: "Customer Service", target: "handoff.cs" },
      { key: "1", label: "Rusak", target: "complaint.collect" },
      { key: "2", label: "Salah", target: "complaint.collect" },
      { key: "3", label: "Tidak biasa", target: "complaint.collect" },
      { key: "4", label: "Kemasan", target: "complaint.collect" },
      { key: "5", label: "Food safety", target: "handoff.food_safety" },
      { key: "6", label: "Lainnya", target: "complaint.collect" },
      { key: "9", label: "Kembali", target: "home" },
    ], "home"),
    "complaint.collect": { id: "complaint.collect", parentId: "complaint", action: "handoff", handoffDestination: "CUSTOMER_SUPPORT", handoffReason: "complaint", intent: "COMPLAINT", risk: "AMBER", templateId: "complaint.collect.v1" },
    other: { id: "other", parentId: "home", action: "handoff", handoffDestination: "CUSTOMER_SUPPORT", handoffReason: "other", intent: "OTHER", risk: "AMBER", templateId: "other.v1" },
    "handoff.cs": { id: "handoff.cs", action: "handoff", handoffDestination: "CUSTOMER_SUPPORT", handoffReason: "human_request", intent: "HUMAN_REQUEST", risk: "RED", templateId: "handoff.queued.v1" },
    "handoff.sales": { id: "handoff.sales", action: "handoff", handoffDestination: "SALES_PARTNERSHIP", handoffReason: "b2b_qualification", intent: "B2B_INTRO", risk: "AMBER", templateId: "handoff.queued.v1" },
    "handoff.food_safety": { id: "handoff.food_safety", action: "handoff", handoffDestination: "FOOD_SAFETY", handoffReason: "food_safety", intent: "FOOD_SAFETY", risk: "RED", templateId: "handoff.queued.v1" },
    "handoff.refund": { id: "handoff.refund", action: "handoff", handoffDestination: "CUSTOMER_SUPPORT", handoffReason: "refund_request", intent: "REFUND_OR_COMPENSATION", risk: "RED", templateId: "handoff.queued.v1" },
    "handoff.complaint": { id: "handoff.complaint", action: "handoff", handoffDestination: "CUSTOMER_SUPPORT", handoffReason: "order_complaint", intent: "COMPLAINT", risk: "AMBER", templateId: "complaint.collect.v1" },
  },
};
